Upgrade to ES v7
Financial-Times/content-rw-elasticsearch pull request #55
Opened 2022-03-14 11:01 UTC by denisacostaq

# Description

## What

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code

## Why

https://financialtimes.atlassian.net/browse/UPPSF-2702

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

- Migrate schema to ES 7.10
- Document type concept have been removed in ES 6

## Scope and particulars of this PR (Please tick all that apply)

- [x] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [x] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2022-03-17 08:56 UTC, atanasdinov requested changes
Let's clear up the commit history by rebasing.

2022-03-17 08:56 UTC, atanasdinov commented on go.mod
> +module github.com/Financial-Times/content-rw-elasticsearch/v7
Major versions are only incremented with a single digit and represent complete overhaul of services or backwards incompatibility of libraries. This should be done in separate respective branches but hasn't been done for this service so I'd rather we keep the old `v2` as the major version.

Some more info related to this: https://go.dev/doc/modules/major-version

2022-03-17 08:56 UTC, atanasdinov commented on pkg/es/service.go
> -		Type(conceptType).
So having the type as part of the model is equivalent to the old `.Type()` call?

2022-03-17 08:56 UTC, atanasdinov commented on pkg/mapper/mapper.go
> +	*model.Type = contentType
Is this correct? Previously this was `conceptType` retrieved from the mapper config. In the configuration and tests possible values for this are `FTCom`, `FTBlogs`, etc. Why is it changed?

2022-03-17 08:56 UTC, atanasdinov commented on configs/migrate.sh
> +#!/usr/bin/env bash
Is this the script that generated the changes to `referenceSchema.json`? Is it reliable?

2022-03-17 09:31 UTC, denisacostaq commented on go.mod
> +module github.com/Financial-Times/content-rw-elasticsearch/v7
Yep, thank you

2022-03-17 09:31 UTC, denisacostaq commented on pkg/es/service.go
> -		Type(conceptType).
No, in ES 6 the "type concept" was removed, but we still need to use this, so this is a way to mimic (differentiate among different document types)
https://www.elastic.co/blog/removal-of-mapping-types-elasticsearch

2022-03-17 09:32 UTC, denisacostaq commented on pkg/mapper/mapper.go
> +	*model.Type = contentType
Good catch, this solves this :smile: 

https://github.com/Financial-Times/content-search-api-port/blob/06d5a0be2d0b630d39d68fbe4188c65628606a7c/service/src/main/java/com/ft/search/platform/api/service/search/elasticsearch/ElasticSearchBuilder.java#L122-L133

2022-03-17 09:32 UTC, denisacostaq commented on configs/migrate.sh
> +#!/usr/bin/env bash
Not really, it was at some point, but for the last changes was too difficult to express it in `jq`, maybe is a good idea to keep it as a documentation that represent a bit the changes, maybe not because is not totally compatible.

2022-03-17 09:39 UTC, atanasdinov commented on pkg/es/service.go
> -		Type(conceptType).
I see, thank you!

2022-09-07 08:44 UTC, atanasdinov approved these changes

2022-09-07 08:49 UTC, martin-stanchev approved these changes

2022-09-07 08:54 UTC, merged

2022-09-07 15:07 UTC, MiroslavGatsanoga commented
🎉 🎉 🎉