Annotations with same predicate are ordered before applying primary t…
Financial-Times/content-rw-elasticsearch pull request #65
Opened 2023-01-09 14:40 UTC by Eng3lFT

# Description

## What

Orders the annotations before setting the primary theme of the Index to be sure is always the same.

## Why

[JIRA ticket](https://financialtimes.atlassian.net/browse/UPPSF-4128).

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [X] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2023-01-12 08:15 UTC, atanasdinov requested changes

2023-01-12 08:15 UTC, atanasdinov commented on pkg/mapper/mapper.go
> +				setPrimaryTheme(model, annotation.PrefLabel, getCmrIDWithFallback(tmeOrganisations, annIDs))
The only thing changing is the first argument of `getCmrIDWithFallback`. I'd suggest to:
- have a single predicate check
- use the switch only to set the TME argument
- have a single `setPrimaryTheme` call.

2023-01-12 08:15 UTC, atanasdinov commented on pkg/mapper/mapper.go
> +		return store[i].ID < store[j].ID
Sorting by ID (i.e. by `"http://api.ft.com/things/{uuid}"` values) seems as arbitrary to me as not having any sorting at all. I'd pick `PrefLabel` or something else as the criteria.

2023-01-12 08:15 UTC, atanasdinov commented on pkg/mapper/mapper.go
> +	var store []schema.Thing
A nitpick but the naming here is off. Could we improve it?

2023-01-12 08:15 UTC, atanasdinov commented on pkg/mapper/mapper.go
> +	for _, annotation := range annotations {
A function called `sortAnnotations` shouldn't be the one responsible for such filtering. Could we rework this a little?

2023-01-12 08:30 UTC, Eng3lFT commented on pkg/mapper/mapper.go
> +		return store[i].ID < store[j].ID
Fair enough, TBH I picked `ID` just for ensure a sorting criteria.

2023-01-12 09:15 UTC, Eng3lFT commented on pkg/mapper/mapper.go
> +	for _, annotation := range annotations {
Totally agree, it does more than just sorting.

2023-01-17 08:19 UTC, atanasdinov commented on pkg/mapper/mapper.go
> +	for _, annotation := range annotations {
Sorry if I wasn't clear enough. I thought it's better to split the filtering and sorting and not do it in the same function in the first place.

2023-01-17 08:19 UTC, atanasdinov commented on pkg/mapper/mapper.go
> +		if annotation.Predicate == predicate {
Do we need this check if we've already filtered the annotations by this predicate?

2023-01-17 08:19 UTC, atanasdinov commented on test/testdata/exampleEnrichedContentModel.json
> -    {
Do we have to drop this test data?

2023-01-17 09:11 UTC, Eng3lFT commented on test/testdata/exampleEnrichedContentModel.json
> -    {
The idea is to have an example without the predicate `http://www.ft.com/ontology/annotation/about` so `cmr_primarytheme` can be [empty](https://github.com/Financial-Times/content-rw-elasticsearch/pull/65/files/56a7d0572fe6b47ce4e8b900609c9e5d1529a42d#diff-bb8bd79eb951625575ebef7ad6b760931a3f35876ee4509d4c38fd0e4592df42R33).

2023-01-17 09:25 UTC, Eng3lFT commented on pkg/mapper/mapper.go
> +	for _, annotation := range annotations {
I would filter in a separate function and sorting may be done in the same function as are only three lines.

2023-01-18 09:08 UTC, martin-stanchev approved these changes

2023-01-23 08:50 UTC, merged