Block Central banking editorial desk
Financial-Times/content-rw-elasticsearch pull request #81
Opened 2024-08-19 10:45 UTC by lokendersinghft

fix

# Description

## What

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code

## Why

Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

## DoD - Ensure all relevant tasks are completed before marking this PR as "Ready for review"

- [ ] Test coverage is not significantly decreased
- [ ] All PR checks have passed
- [ ] Changes are deployed on dev before asking for review
- [ ] Documentations remains up-to-date
  - [ ] OpenAPI definition file is updated
  - [ ] README file is updated
  - [ ] Documentation is updated in upp-docs and upp-public-docs
  - [ ] Architecture diagrams are updated

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2024-08-20 05:14 UTC, todor-videv1 commented on pkg/message/message_handler.go
> +		log.WithField("reasons", res.Reasons).Infof("Skipping content")
**praise**: Good catch.

2024-08-20 05:21 UTC, todor-videv1 commented on pkg/message/message_handler_test.go
> +	opaClient := opa.NewOpenPolicyAgentClient(os.Getenv("OPA_URL"), paths, opa.WithLogger(uppLogger))
**question**: Shouldn't we check whether the env variable is actually accessible (has been set)? What happens if you forget to set it and run the tests?

2024-08-20 05:22 UTC, todor-videv1 commented on pkg/message/message_handler_test.go
> +	log.Println(model.Body)
**issue**: I think this might be unnecessary.

2024-08-20 05:26 UTC, todor-videv1 commented on pkg/policy/agent_test.go
**question**: There are several comments that are left over by the previous implementation, they do not seem to be relevant anymore. Stuff like "// query field is informative and is not being used during tests evaluation". Am I right?

2024-08-20 05:33 UTC, todor-videv1 commented on .circleci/config.yml
> +          command: export GITHUB_BRANCH=${CIRCLE_BRANCH} && docker-compose -f docker-compose-tests.yaml up -d --build && docker logs -f test-runner && export TESTS_STATUS_CODE=$(docker inspect test-r
**question**: Why do we set GITHUB_BRANCH?

2024-08-20 05:36 UTC, todor-videv1 requested changes
Setting this to "Request changes" so you can take a look at the comments, in any case it is an okay restructuring of the tests.

2024-08-20 06:07 UTC, lokendersinghft commented on pkg/message/message_handler_test.go
> +	opaClient := opa.NewOpenPolicyAgentClient(os.Getenv("OPA_URL"), paths, opa.WithLogger(uppLogger))
yes..there should be a check and a default url. Also I am repeating this code in agent_test.go, so will extract it in other file. [Ref](https://github.com/Financial-Times/notifications-push/blob/master/access/evaluate_test_helper.go)

2024-08-20 06:08 UTC, lokendersinghft commented on pkg/message/message_handler_test.go
> +	log.Println(model.Body)
It is unnecessary.. will be removed.

2024-08-20 06:08 UTC, lokendersinghft commented on pkg/policy/agent_test.go
yes, you are right. These are unnecessary comments and  will be removed.

2024-08-20 13:26 UTC, todor-videv1 approved these changes

2024-08-20 13:27 UTC, todor-videv1 approved these changes

2024-08-21 05:39 UTC, antoanFT approved these changes

2024-08-21 07:37 UTC, antoanFT submitted a review, later dismissed

2024-08-21 08:57 UTC, antoanFT approved these changes

2024-08-21 10:40 UTC, todor-videv1 approved these changes

2024-08-21 11:20 UTC, merged